---
title: "Combined_graphs_0515_2021"
author: "Troy McDiarmid"
date: "15/05/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(readxl)
library(UpSetR)

```


```{r}
# library
combined_phenos <- read_excel("/Users/troymcdiarmid/Downloads/Combined_reverse_data_0515_2021.xlsx")

##Calculating sum of sig features in each feature class

pheno_counts <- combined_phenos %>% 
  mutate(morphology = (length + width + area + midline + morphwidth)) %>% 
  mutate(baseline = (pathlen + bias + dir + angular + aspect + kink + crab + speed + curve)) %>% 
  mutate(sensitivity = (initRespPb + initRespDuration + initRespSpeed + initRespDistance)) %>% 
  mutate(learning = (habituationPb + habituationDuration + habituationSpeed + habituationDistance)) %>% 
  mutate(recovery = (spontPb + spontDuration + spontSpeed + spontDistance)) 

##Order genotype factor

pheno_counts$Condition <- factor(pheno_counts$Condition, levels = pheno_counts$Condition)

##Gather pheno_counts

pheno_counts <- pheno_counts %>% 
  gather(`morphology`, `baseline`, `sensitivity`, `learning`, `recovery`, key = "feature_class", value = "count")
##order factors

pheno_counts$feature_class <- factor(pheno_counts$feature_class,
    levels = c('recovery', 'learning', 'sensitivity', 'baseline', 'morphology'), ordered = TRUE)


##Make specific plots for each gene

pheno_counts_unc3 <- pheno_counts %>% 
  filter(Genotype == "unc3")

ggplot(data = pheno_counts_unc3) + 
  geom_bar(aes(x = Condition, y = count, fill = feature_class), stat = "identity") +
  theme_classic() +
  scale_y_continuous(position = "right") +
    ylim(0,15) +
  labs(y = "", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
    theme(axis.line.y = element_line(colour = 'black', size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.text.x = element_text(hjust = 1)) +
    theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial Bold", colour = "black", size = 30)) +
  scale_fill_manual(values=c("#76b6f4", "#d1e6fb", "dodgerblue2", "gray39", "black")) 

ggsave("ASD_Reverse_Pheno_counts_unc3.jpeg", width = 3.5, height = 12, path = "/Users/troymcdiarmid/Desktop/")

pheno_counts_dhc1 <- pheno_counts %>% 
  filter(Genotype == "dhc1")

ggplot(data = pheno_counts_dhc1) + 
  geom_bar(aes(x = Condition, y = count, fill = feature_class), stat = "identity") +
  theme_classic() +
  scale_y_continuous(position = "right") +
    ylim(0,15) +
  labs(y = "", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
    theme(axis.line.y = element_line(colour = 'black', size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.text.x = element_text(hjust = 1)) +
    theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial Bold", colour = "black", size = 30)) +
  scale_fill_manual(values=c("#76b6f4", "#d1e6fb", "dodgerblue2", "gray39", "black")) 

ggsave("ASD_Reverse_Pheno_counts_dhc1.jpeg", width = 3.5, height = 12, path = "/Users/troymcdiarmid/Desktop/")

pheno_counts_unc86 <- pheno_counts %>% 
  filter(Genotype == "unc86")

ggplot(data = pheno_counts_unc86) + 
  geom_bar(aes(x = Condition, y = count, fill = feature_class), stat = "identity") +
  theme_classic() +
  scale_y_continuous(position = "right") +
  ylim(0,15) +
  labs(y = "", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
    theme(axis.line.y = element_line(colour = 'black', size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.text.x = element_text(hjust = 1)) +
    theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial Bold", colour = "black", size = 30)) +
  scale_fill_manual(values=c("#76b6f4", "#d1e6fb", "dodgerblue2", "gray39", "black")) 

ggsave("ASD_Reverse_Pheno_counts_unc86.jpeg", width = 3.5, height = 12, path = "/Users/troymcdiarmid/Desktop/")


pheno_counts_unc86 <- pheno_counts %>% 
  filter(Genotype == "nlg1")

ggplot(data = pheno_counts_unc86) + 
  geom_bar(aes(x = Condition, y = count, fill = feature_class), stat = "identity") +
  theme_classic() +
  scale_y_continuous(position = "right") +
  ylim(0,15) +
  labs(y = "", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
    theme(axis.line.y = element_line(colour = 'black', size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.text.x = element_text(hjust = 1)) +
    theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial Bold", colour = "black", size = 30)) +
  scale_fill_manual(values=c("#76b6f4", "#d1e6fb", "dodgerblue2", "gray39", "black")) 

ggsave("ASD_Reverse_Pheno_counts_nlg1.jpeg", width = 3.5, height = 12, path = "/Users/troymcdiarmid/Desktop/")


```





##Upset plot



```{r}
# Filtering for a continous deg groups then making the upset plot

combined_phenos_C <- as.data.frame(combined_phenos) %>% 
  select(-Genotype) %>% 
  filter(Condition %in% c("unc3_C", "neur_dhc1_C", "unc86_C", "nlg1_C"))
  

rownames(combined_phenos_C) <- combined_phenos_C$Condition
combined_phenos_C$Condition <- NULL


combined_phenos_C_transpose <- as.data.frame(t(as.matrix(combined_phenos_C)))

upset(combined_phenos_C_transpose, order.by = "degree", decreasing = c(F), empty.intersections = "on")

ggsave("continous_upset_0516_2021.jpeg", path = "/Users/troymcdiarmid/Desktop/")


##Filterning for developmental degradation/rescue groups

combined_phenos <- read_excel("/Users/troymcdiarmid/Downloads/Combined_reverse_data_upset_0515_2021.xlsx")

##Calculating sum of sig features in each feature class

pheno_counts <- combined_phenos %>% 
  mutate(morphology = (length + width + area + midline + morphwidth)) %>% 
  mutate(baseline = (pathlen + bias + dir + angular + aspect + kink + crab + speed + curve)) %>% 
  mutate(sensitivity = (initRespPb + initRespDuration + initRespSpeed + initRespDistance)) %>% 
  mutate(learning = (habituationPb + habituationDuration + habituationSpeed + habituationDistance)) %>% 
  mutate(recovery = (spontPb + spontDuration + spontSpeed + spontDistance)) 

##Order genotype factor

pheno_counts$Condition <- factor(pheno_counts$Condition, levels = pheno_counts$Condition)

##Gather pheno_counts

pheno_counts <- pheno_counts %>% 
  gather(`morphology`, `baseline`, `sensitivity`, `learning`, `recovery`, key = "feature_class", value = "count")
##order factors

pheno_counts$feature_class <- factor(pheno_counts$feature_class,
    levels = c('recovery', 'learning', 'sensitivity', 'baseline', 'morphology'), ordered = TRUE)

combined_phenos_D <- as.data.frame(combined_phenos) %>% 
  select(-Genotype) %>% 
  filter(Condition %in% c("unc3_D", "neur_dhc1_D", "unc86_D", "nlg1_D"))
  

rownames(combined_phenos_D) <- combined_phenos_D$Condition
combined_phenos_D$Condition <- NULL


combined_phenos_D_transpose <- as.data.frame(t(as.matrix(combined_phenos_D)))

upset(combined_phenos_D_transpose, order.by = "degree", decreasing = c(F), empty.intersections = "on")

ggsave("reverse_upset_0516_2021.jpeg", path = "/Users/troymcdiarmid/Desktop/")

```




