---
title: "unc86_reversibility"
author: "Troy McDiarmid"
date: "31/05/2020"
output: html_document
---


```{r setup, include=FALSE}
##Load in them libraries
library(tidyverse)

```






L4 recovery analysis run 2






```{r setup, include=FALSE}
##Bash loop to call choreography to output reversals from each tracker plate data file generated by the tracker

for folder in $( ls ); do java -jar /Users/troymcdiarmid/Desktop/Chore.jar --segment --shadowless --pixelsize 0.027 --minimum-move-body 2 --minimum-time 20 --output width,length,morphwidth,curve,area,midline,pathlen,bias,dir,angular,aspect,kink,crab,speed --plugin Reoutline::despike --plugin Respine --plugin MeasureReversal::tap::dt=1::collect=0.5 $folder; done

##Bash argument to grep all .trv choreography output files into a summary of reversals
grep -H '[.]*' $(find . -name '*.rev') > data.srev
cd ../..
```


```{r}
##Baseline N2 vs unc-86::AID::GFP test

##Read in summary of reversal data fill (data.srev) 

setwd("/Volumes/SAMWISE/Troy/reversibility/unc_86/unc86_AID_1009_2020/data")
cleanrawsrev <- read_table2("data.srev", col_names = c("plate_id", "already_rev", "not_rev", "rev", "rev_dist", "dist_sd", "dist_sem", "dist_0_quart", "dist_1st_quart", "dist_2nd_quart", "dist_3rd_quart", "dsit_100th_percentile", "rev_dur", "dur_sd", "dur_sem", "dur_0_quart", "dur_1st_quart", "dur_2nd_quart", "dur_3rd_quart", "dur_100th_percentile"))
cleanrawsrev <- cleanrawsrev %>% 
  separate(plate_id, into = c("garbage", "plate_id", "genotype"), sep ="/") %>%
  separate(genotype, into = c("genotype", "time"), sep = ":")  %>% 
  separate(genotype, into = c("genotype", "tracker"), sep = "s_") %>% 
  separate(genotype, into = c("genotype", "growth_conditions"), sep = "_") %>%
  separate(tracker, into = c("tracker", "date"), sep = "1") %>%
  select(plate_id:dur_100th_percentile)

##Filtering to not include tracker C becuase it delivered faulty taps

cleanrawsrev <- cleanrawsrev %>%
  filter(!tracker == "C")

##Optional Code to rename your factors

cleanrawsrev$genotype <- recode(cleanrawsrev$genotype, `N2` = "Wild-type (N2)")

##Make time numeric and round time 

cleanrawsrev <- cleanrawsrev %>% mutate(time = as.numeric(time)) %>% 
  mutate(time = round(time, digits = 0)) 

##Calculate reversal probability

cleanrawsrev <- cleanrawsrev %>% 
  mutate(rev_prob = rev / (not_rev + rev)) 

##optional code to remove any bad observtions and/or plates

cleanrawsrev <- cleanrawsrev %>% 
  filter(!(rev_dist == "0")) 
cleanrawsrev <- cleanrawsrev %>% 
  filter(!(time == "659"))
cleanrawsrev <- cleanrawsrev %>% 
  filter(!(plate_id == "20201009_132231"))  

##Calculate reversal speed 

cleanrawsrev <- cleanrawsrev %>%
  mutate(rev_speed = rev_dist / rev_dur) 

##Reorder factors

cleanrawsrev$genotype <- factor(cleanrawsrev$genotype,
    levels = c('unc86N', 'unc86C25', 'unc86C4', 'unc86A25', 'unc86D25', 'N2C1', 'N2C4', ordered = TRUE))

##Mean rev data

mean_cleanrawsrev <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarize_all(mean) 

##Add stim number NOTE: this must be changed to fit your experiment parameters 

mean_cleanrawsrev$stimulus_num <- rep(1:31, times = 7) 

##SD calcs

prob_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(prob_sd = sd(rev_prob))
dur_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dur_sd = sd(rev_dur))
speed_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(speed_sd = sd(rev_speed))
dist_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dist_sd = sd(rev_dist))

##SEM calcs

prob_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(prob_sem = sd(rev_prob)/sqrt(length(rev_prob)))
dur_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dur_sem = sd(rev_dur)/sqrt(length(rev_dur)))
dist_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dist_sem = sd(rev_dist)/sqrt(length(rev_dist)))
speed_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(speed_sem = sd(rev_speed)/sqrt(length(rev_speed)))


```


```{r}
##Plots of mean reversal probability nlg-1::AID::GFP VS N2 both with no Auxin treatment

##Habituation unc-86::AID::GFP continous degradation vs. non-treated

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_L4_AID_C_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Habituation unc-3::AID::GFP continous degradation vs. non-treated and developmental degradtion/adult recovery

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86D25"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86D25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_L4_AID_C_D_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86D25"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86D25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_D_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86D25"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86D25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_D_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Habituation unc-3::AID::GFP continous degradation vs. non-treated and adult inactivation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_L4_AID_C_A_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_A_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_A_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Habituation unc-3::AID::GFP continous degradation vs. adult and developmental degradation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25", "unc86D25"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25", "unc86D25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_L4_AID_C_A_D_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25", "unc86D25"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25", "unc86D25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_A_D_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25", "unc86D25"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86A25", "unc86D25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C_A_D_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Added graphs for 4mM continous comparison

##Habituation unc-3::AID::GFP continous degradation vs. adult and developmental degradation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86C4"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86C4"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "red")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_L4_AID_C25_C4_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86C4"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86C4"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "red")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C25_C4_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86C4"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("unc86N", "unc86C25", "unc86C4"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "red")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_L4_AID_C25_C4_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/habituation")


```



```{r}

##Basic morphology features analysis

##Bash loop to output reversals and basic morphology from tracker plates (to be run in terminal)

for folder in $( ls ); do java -jar /Users/troymcdiarmid/Desktop/Chore.jar --segment --shadowless --pixelsize 0.027 --minimum-move-body 2 --minimum-time 20 --output width,length,morphwidth,curve,area,midline,pathlen,bias,dir,angular,aspect,kink,crab,speed --plugin Reoutline::despike --plugin Respine --plugin MeasureReversal::tap::dt=1::collect=0.5 $folder; done

##Bash argument to grep all .dat files into a summary of morphology (to be run in terminal)

grep -H '[.]*' $(find . -name '*.dat') > data.smorph

cd ../..

```


```{r}
##The following code creates a dataframe with all morphology and baseline locomotion measures throughout the tracking session.

##Comand to read .smorph file in 

setwd("/Volumes/SAMWISE/Troy/reversibility/unc_86/unc86_AID_1009_2020/data")

rawsmorph <- read_table2("data.smorph", col_names = c("plate_id", "width", "length", "morphwidth", "curve", "area", "midline", "pathlen", "bias", "dir", "angular", "aspect", "kink", "crab", "speed"))

cleanrawsmorph <- rawsmorph %>% 
  separate(plate_id, into = c("garbage", "plate_id", "genotype"), sep ="/") %>%
  separate(genotype, into = c("genotype", "time"), sep = ":") %>% 
  separate(genotype, into = c("genotype", "tracker"), sep = "s_") %>% 
  separate(tracker, into = c("tracker", "date"), sep = "1") %>% 
  separate(genotype, into = c("genotype", "growth_conditions"), sep = "_") 
   

##Filtering not for tracker C becuase it delivered faulty taps

cleanrawsmorph <- cleanrawsmorph %>% 
  filter(!tracker == "C")

  
####Make time numeric and round time

cleanrawsmorph <- cleanrawsmorph %>% mutate(time = as.numeric(time)) %>% 
  mutate(time = round(time, digits = 0)) 

##Ordering the genotype factor for plotting
    
cleanrawsmorph$genotype <- factor(cleanrawsmorph$genotype,
    levels = c('unc86N', 'unc86C4', 'unc86C25', 'unc86A25', 'unc86D25', 'N2C', 'N2C4', ordered = TRUE))

##Filter for relevant groups

cleanrawsmorph <- cleanrawsmorph %>% 
    filter(genotype %in% c('unc86N', 'unc86C25', 'unc86A25', 'unc86D25'))


##Filtering to exclude first 10s when the tracker has yet to calculate conistent measurements for certain metrics.

cleanrawsmorph <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 10, 1199))


```


```{r}
##Code to calculate mean of morphology metrics

mean_cleanrawsmorph_whole_session <- cleanrawsmorph %>% 
  select(genotype, time, width:speed) 

mean_cleanrawsmorph_whole_session <- mean_cleanrawsmorph_whole_session %>%  
  group_by(genotype, time) %>%
  summarize_all(mean) 

#Plots of morphology metrics for all groups

ggplot(mean_cleanrawsmorph_whole_session, aes(time, speed, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 0.3), breaks = c(0,0.1,0.2,0.3)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Speed (mm/s)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_speed_trace_l4.jpeg", width = 3.5, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")


ggplot(mean_cleanrawsmorph_whole_session, aes(time, curve, colour = genotype)) + 
geom_line(size = 0.3) +
  scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 50), breaks = c(0,10,20,30,40,50)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Curvature (radians)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_curve_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, kink, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0,100), breaks = c(0,25,50,75,100)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Kink (radians)", x = "Time (S)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_kink_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, length, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 1.25), breaks = c(0,0.25,0.5,0.75,1.0,1.25)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Length (mm)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_Length_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, midline, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0.0, 1.5), breaks = c(0.0,0.25,0.5,0.75,1.00,1.25,1.5)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Midline length (mm)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_midline_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, width, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 0.5), breaks = c(0.0,0.1,0.2,0.3,0.4,0.5)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Width (mm)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_width_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, pathlen, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 25), breaks = c(0,5,10,15,20,25)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Pathlength (mm)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_pathlength_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, bias, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(-1, 1), breaks = c(-1.0,-0.5,0,0.5,1.0)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Direction bias", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_bias_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, dir, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 0.06), breaks = c(0,0.02,0.04,0.06)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Direction change", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_dir_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, crab, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 0.06), breaks = c(0,0.02,0.04,0.06)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Horizontal speed (mm/s)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_crab_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

ggplot(mean_cleanrawsmorph_whole_session, aes(time, aspect, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0.0, 0.6), breaks = c(0,0.2,0.4,0.6)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Aspect (width to length ratio)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_aspect_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")


ggplot(mean_cleanrawsmorph_whole_session, aes(time, angular, colour = genotype)) + 
geom_line(size = 0.3) +
   scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 30), breaks = c(0,10,20,30)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 1260), breaks = c(0,300,600,900,1200)) +
  theme_classic() +
  labs(y = "Angular speed (radians/second)", x = "Time (s)") +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12)) +
  theme(axis.title = element_text(family="Arial", colour = "black", size = 12)) +
ggsave("unc86_rev_angular_trace_l4.jpeg", width = 3, height = 2.5, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/morphology")

```




```{r}

##Calculating significance accross all morphology metrics for dhc-1 heatmap


##Code to calculate mean of morphology metrics accross plates

cleanrawsmorph_baseline <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 300, 599))

mean_cleanrawsmorph <- cleanrawsmorph_baseline %>% 
  dplyr::select(genotype, plate_id, width:speed) 

mean_cleanrawsmorph <- mean_cleanrawsmorph %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 

##Calculating absolute means and Sds across genomes 

genotype_means <- mean_cleanrawsmorph %>% 
  summarise_all(mean) 

genotype_sds <- mean_cleanrawsmorph %>% 
  summarise_all(sd) 

##Calculating stats

pairwise.t.test(x = mean_cleanrawsmorph$length, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$width, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$midline, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$morphwidth, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$area, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$pathlen, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$bias, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$dir, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$angular, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$aspect, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$kink, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$crab, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH") 
pairwise.t.test(x = mean_cleanrawsmorph$speed, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$curve, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")

ggplot(mean_cleanrawsmorph, aes(genotype, length, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, width, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, midline, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, morphwidth, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, area, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, pathlen, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, bias, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, dir, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, angular, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, aspect, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, kink, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, crab, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, curve, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)

##Calculating significance for all sensory/learning metrics for dhc-1 heatmap 

Initial_revs <- cleanrawsrev %>%
  filter(time %in% c(600)) %>% 
  filter(genotype %in% c('unc86N', 'unc86C25', 'unc86A25', 'unc86D25'))

mean_initial_revs <- Initial_revs %>% 
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 
  

pairwise.t.test(x = mean_initial_revs$rev_prob, g = mean_initial_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_initial_revs$rev_dur, g = mean_initial_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_initial_revs$rev_dist, g = mean_initial_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_initial_revs$rev_speed, g = mean_initial_revs$genotype, p.adjust.method = "BH")

ggplot(mean_initial_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_initial_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_initial_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_initial_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)


Final_revs <- cleanrawsrev %>%
  filter(time %in% c(870:890)) %>% 
  filter(genotype %in% c('unc86N', 'unc86C25', 'unc86A25', 'unc86D25'))

mean_final_revs <- Final_revs %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 


pairwise.t.test(x = mean_final_revs$rev_prob, g = mean_final_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_final_revs$rev_dur, g = mean_final_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_final_revs$rev_speed, g = mean_final_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_final_revs$rev_dist, g = mean_final_revs$genotype, p.adjust.method = "BH")

ggplot(mean_final_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_final_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_final_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_final_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)



Spont_revs <- cleanrawsrev %>%
  filter(time %in% c(1190)) %>% 
  filter(genotype %in% c('unc86N', 'unc86C25', 'unc86A25', 'unc86D25'))

mean_spont_revs <- Spont_revs %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 


pairwise.t.test(x = mean_spont_revs$rev_prob, g = mean_spont_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_spont_revs$rev_dur, g = mean_spont_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_spont_revs$rev_dist, g = mean_spont_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_spont_revs$rev_speed, g = mean_spont_revs$genotype, p.adjust.method = "BH")


ggplot(mean_spont_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_spont_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_spont_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_spont_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)


all_revs <- cleanrawsrev %>%
  filter(genotype %in% c('unc86N', 'unc86C25', 'unc86A25', 'unc86D25')) 

mean_all_revs <- all_revs %>% 
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 

pairwise.t.test(x = mean_all_revs$rev_prob, g = mean_all_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_all_revs$rev_speed, g = mean_all_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_all_revs$rev_dur, g = mean_all_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_all_revs$rev_dist, g = mean_all_revs$genotype, p.adjust.method = "BH")

ggplot(mean_all_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_all_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_all_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_all_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)


```

```{r}
##First ungroup the dataframe for statistical testing

UG_mean_cleanrawsmorph <- ungroup(mean_cleanrawsmorph) 

##Compute the t-statistics and p-values for all features

Length_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(length ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(length ~ genotype,
   data = UG_mean_cleanrawsmorph) 
length_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
length_results <- length_tstat_DF %>% 
  left_join(Length_pwt, by = "genotype") 

width_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(width ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(width ~ genotype,
   data = UG_mean_cleanrawsmorph) 
width_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
width_results <- width_tstat_DF %>% 
  left_join(width_pwt, by = "genotype") 

midline_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(midline ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(midline ~ genotype,
   data = UG_mean_cleanrawsmorph) 
midline_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
midline_results <- midline_tstat_DF %>% 
  left_join(midline_pwt, by = "genotype") 

morphwidth_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(morphwidth ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(morphwidth ~ genotype,
   data = UG_mean_cleanrawsmorph) 
morphwidth_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
morphwidth_results <- morphwidth_tstat_DF %>% 
  left_join(morphwidth_pwt, by = "genotype") 

area_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(area ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(area ~ genotype,
   data = UG_mean_cleanrawsmorph) 
area_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
area_results <- area_tstat_DF %>% 
  left_join(area_pwt, by = "genotype")

pathlen_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(pathlen ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(pathlen ~ genotype,
   data = UG_mean_cleanrawsmorph) 
pathlen_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
pathlen_results <- pathlen_tstat_DF %>% 
  left_join(pathlen_pwt, by = "genotype")

bias_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(bias ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(bias ~ genotype,
   data = UG_mean_cleanrawsmorph) 
bias_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
bias_results <- bias_tstat_DF %>% 
  left_join(bias_pwt, by = "genotype")

dir_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(dir ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(dir ~ genotype,
   data = UG_mean_cleanrawsmorph) 
dir_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
dir_results <- dir_tstat_DF %>% 
  left_join(dir_pwt, by = "genotype")

angular_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(angular ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(angular ~ genotype,
   data = UG_mean_cleanrawsmorph) 
angular_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
angular_results <- angular_tstat_DF %>% 
  left_join(angular_pwt, by = "genotype")

aspect_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(aspect ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(aspect ~ genotype,
   data = UG_mean_cleanrawsmorph) 
aspect_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
aspect_results <- aspect_tstat_DF %>% 
  left_join(aspect_pwt, by = "genotype")

kink_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(kink ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(kink ~ genotype,
   data = UG_mean_cleanrawsmorph) 
kink_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
kink_results <- kink_tstat_DF %>% 
  left_join(kink_pwt, by = "genotype")

crab_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(crab ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(crab ~ genotype,
   data = UG_mean_cleanrawsmorph) 
crab_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
crab_results <- crab_tstat_DF %>% 
  left_join(crab_pwt, by = "genotype")

speed_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(speed ~ genotype,
   data = UG_mean_cleanrawsmorph) 
speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
speed_results <- speed_tstat_DF %>% 
  left_join(speed_pwt, by = "genotype")

curve_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(curve ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(curve ~ genotype,
   data = UG_mean_cleanrawsmorph) 
curve_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
curve_results <- curve_tstat_DF %>% 
  left_join(curve_pwt, by = "genotype")


##Now ungrouping the initial revs

UG_mean_initial_revs <- ungroup(mean_initial_revs)

##Then calculating those four statistics 

init_rev_prob_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_prob_results <- init_rev_prob_tstat_DF %>% 
  left_join(init_rev_prob_pwt, by = "genotype")

init_rev_dur_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_dur_results <- init_rev_prob_tstat_DF %>% 
  left_join(init_rev_dur_pwt, by = "genotype")

init_rev_speed_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_speed_results <- init_rev_speed_tstat_DF %>% 
  left_join(init_rev_speed_pwt, by = "genotype")


init_rev_dist_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_dist_results <- init_rev_dist_tstat_DF %>% 
  left_join(init_rev_dist_pwt, by = "genotype")

init_rev_results <- rbind(init_rev_prob_results, init_rev_dur_results, init_rev_speed_results, init_rev_dist_results) 

init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_prob")] <- "init_rev_prob"
init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_dur")] <- "init_rev_dur"
init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_speed")] <- "init_rev_speed"
init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_dist")] <- "init_rev_dist"


##Then caclulating hab level

UG_mean_final_revs <- ungroup(mean_final_revs)

final_rev_prob_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_final_revs) 
final_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_prob_results <- final_rev_prob_tstat_DF %>% 
  left_join(final_rev_prob_pwt, by = "genotype")

final_rev_dur_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_final_revs) 
final_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_dur_results <- final_rev_dur_tstat_DF %>% 
  left_join(final_rev_dur_pwt, by = "genotype")

final_rev_speed_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_final_revs) 
final_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_speed_results <- final_rev_speed_tstat_DF %>% 
  left_join(final_rev_speed_pwt, by = "genotype")


final_rev_dist_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_final_revs) 
final_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_dist_results <- final_rev_dist_tstat_DF %>% 
  left_join(final_rev_dist_pwt, by = "genotype")

final_rev_results <- rbind(final_rev_prob_results, final_rev_dur_results, final_rev_speed_results, final_rev_dist_results) 

final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_prob")] <- "final_rev_prob"
final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_dur")] <- "final_rev_dur"
final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_speed")] <- "final_rev_speed"
final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_dist")] <- "final_rev_dist"

##Then caclulating spont revs

UG_mean_spont_revs <- ungroup(mean_spont_revs)

spont_rev_prob_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_prob_results <- spont_rev_prob_tstat_DF %>% 
  left_join(spont_rev_prob_pwt, by = "genotype")

spont_rev_dur_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_dur_results <- spont_rev_dur_tstat_DF %>% 
  left_join(spont_rev_dur_pwt, by = "genotype")

spont_rev_speed_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_speed_results <- spont_rev_speed_tstat_DF %>% 
  left_join(spont_rev_speed_pwt, by = "genotype")


spont_rev_dist_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_dist_results <- spont_rev_dist_tstat_DF %>% 
  left_join(spont_rev_dist_pwt, by = "genotype")

spont_rev_results <- rbind(spont_rev_prob_results, spont_rev_dur_results, spont_rev_speed_results, spont_rev_dist_results) 

spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_prob")] <- "spont_rev_prob"
spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_dur")] <- "spont_rev_dur"
spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_speed")] <- "spont_rev_speed"
spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_dist")] <- "spont_rev_dist"


##Then caclulating all revs

UG_mean_all_revs <- ungroup(mean_all_revs)

all_rev_prob_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_all_revs) 
all_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_prob_results <- all_rev_prob_tstat_DF %>% 
  left_join(all_rev_prob_pwt, by = "genotype")

all_rev_dur_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_all_revs) 
all_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_dur_results <- all_rev_dur_tstat_DF %>% 
  left_join(all_rev_dur_pwt, by = "genotype")

all_rev_speed_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_all_revs) 
all_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_speed_results <- all_rev_speed_tstat_DF %>% 
  left_join(all_rev_speed_pwt, by = "genotype")


all_rev_dist_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "unc86N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_all_revs) 
all_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_dist_results <- all_rev_dist_tstat_DF %>% 
  left_join(all_rev_dist_pwt, by = "genotype")

all_rev_results <- rbind(all_rev_prob_results, all_rev_dur_results, all_rev_speed_results, all_rev_dist_results) 

all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_prob")] <- "all_rev_prob"
all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_dur")] <- "all_rev_dur"
all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_speed")] <- "all_rev_speed"
all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_dist")] <- "all_rev_dist"

##Combining everything together

results <- rbind(length_results, width_results, midline_results, morphwidth_results, area_results, pathlen_results, bias_results, dir_results, angular_results, aspect_results, kink_results, crab_results, speed_results, curve_results, init_rev_results, final_rev_results, spont_rev_results, all_rev_results) %>% rename(condition = genotype, t_statistic = statistic, control_n = n1, treatment_condition_n = n2) %>% 
  mutate(p_f = p.adj)

results$p_f[results$p_f > 0.01] <- 0
results$p_f[results$p_f > 0] <- 1

results <- results %>% 
  mutate(plot_sig_tstat = t_statistic*p_f)

##Writing CSV of results

unc86_L4_results <- results %>% 
  select(!"p.adj.signif")

write_csv(unc86_L4_results, "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/unc86_l4_results.csv")

##creating a transposed version for heatmapping

results_mat <- results %>% 
  select(condition, phenotype, t_statistic) %>% 
  pivot_wider(names_from = phenotype, values_from = t_statistic) %>%
  mutate(aspect = aspect*0) %>% 
  as.matrix()

##Adding colnames for heatmap

results_mat2 <- results_mat[,2:31]

colnames_mat <- results_mat[,2:31]


results_mat2 <- matrix(as.numeric(results_mat2), ncol = ncol(results_mat2))

colnames(results_mat2) <- colnames(colnames_mat)
rownames(results_mat2) <- results_mat[,1]

##plotting

col_fun = colorRamp2(c(-20, 0, 20), c("dodgerblue", "black", "yellow"))

Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"))

##Calculate degree of rescue 

abs_continous_effect_mat <- abs(results_mat2)
abs_continous_effect_mat <- t(abs_continous_effect_mat[1,])
abs_rescue_level_mat <- abs(results_mat2)
abs_rescue_level_mat <- t(abs_rescue_level_mat[3,])

rescue_amount_mat <- abs_continous_effect_mat-abs_rescue_level_mat
rescue_amount_mat[rescue_amount_mat < 0] <- 0

col_fun = colorRamp2(c(0, 5), c("white", "#86A790"))

png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/unc86_rescue_amount_heatmap.png", width=1800, height=600, res=300)
 ht <- Heatmap(rescue_amount_mat, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.25, "mm"), show_row_names = FALSE)
 draw(ht, show_heatmap_legend = FALSE)
 dev.off()
 
png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/unc86_rescue_amount_heatmap_leg.png", width=2000, height=600, res=300)
 ht <- Heatmap(rescue_amount_mat, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.25, "mm"))
 draw(ht)
 dev.off()

##Capping t-statistics 

results_mat2[results_mat2 < -5] <- -5
results_mat2[results_mat2 > 5] <- 5
  
##Making the heatmap

col_fun = colorRamp2(c(-5, 0, 5), c("dodgerblue", "black", "yellow"))

Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"))


##Plotting only significant values 

results_mat <- results %>% 
  select(condition, phenotype, plot_sig_tstat) %>% 
  pivot_wider(names_from = phenotype, values_from = plot_sig_tstat) %>% 
  mutate(aspect = aspect*0) %>%
  as.matrix()

results_mat2 <- results_mat[,2:31]

colnames_mat <- results_mat[,2:31]


results_mat2 <- matrix(as.numeric(results_mat2), ncol = ncol(results_mat2))

colnames(results_mat2) <- colnames(colnames_mat)
rownames(results_mat2) <- results_mat[,1]

##Making the heatmap

results_mat2[results_mat2 < -10] <- -10
results_mat2[results_mat2 > 10] <- 10

col_fun = colorRamp2(c(-10, 0, 10), c("dodgerblue", "black", "yellow"))

png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/unc86_heatmap.png", width=1800, height=600, res=300)
 ht <- Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"), show_row_names = FALSE)
 draw(ht, show_heatmap_legend = FALSE)
 dev.off()

png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/unc86_heatmap_leg.png", width=2000, height=600, res=300)
 ht <- Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"))
 draw(ht)
 dev.off()

```









unc-86 1 day rescue rerun 









```{r setup, include=FALSE}
##Bash loop to call choreography to output reversals from each tracker plate data file generated by the tracker

for folder in $( ls ); do java -jar /Users/troymcdiarmid/Desktop/Chore.jar --segment --shadowless --pixelsize 0.027 --minimum-move-body 2 --minimum-time 20 --output width,length,morphwidth,curve,area,midline,pathlen,bias,dir,angular,aspect,kink,crab,speed --plugin Reoutline::despike --plugin Respine --plugin MeasureReversal::tap::dt=1::collect=0.5 $folder; done

##Bash argument to grep all .trv choreography output files into a summary of reversals
grep -H '[.]*' $(find . -name '*.rev') > data.srev
cd ../..
```


```{r}
##Baseline N2 vs unc-86::AID::GFP test

##Read in summary of reversal data fill (data.srev) 

setwd("/Volumes/SAMWISE/Troy/reversibility/unc_86/VG937_1day_0212_2021/data")
cleanrawsrev <- read_table2("data.srev", col_names = c("plate_id", "already_rev", "not_rev", "rev", "rev_dist", "dist_sd", "dist_sem", "dist_0_quart", "dist_1st_quart", "dist_2nd_quart", "dist_3rd_quart", "dsit_100th_percentile", "rev_dur", "dur_sd", "dur_sem", "dur_0_quart", "dur_1st_quart", "dur_2nd_quart", "dur_3rd_quart", "dur_100th_percentile"))
cleanrawsrev <- cleanrawsrev %>% 
  separate(plate_id, into = c("garbage", "plate_id", "genotype"), sep ="/") %>%
  separate(genotype, into = c("genotype", "time"), sep = ":")  %>% 
  separate(genotype, into = c("genotype", "tracker"), sep = "s_") %>% 
  separate(genotype, into = c("genotype", "growth_conditions"), sep = "_") %>%
  separate(tracker, into = c("tracker", "date"), sep = "0") %>%
  select(plate_id:dur_100th_percentile)

##Filtering to not include tracker C becuase it delivered faulty taps

cleanrawsrev <- cleanrawsrev %>%
  filter(!tracker == "C") 

##Optional Code to rename your factors

cleanrawsrev$genotype <- recode(cleanrawsrev$genotype, `N2` = "Wild-type (N2)")

##Make time numeric and round time 

cleanrawsrev <- cleanrawsrev %>% mutate(time = as.numeric(time)) %>% 
  mutate(time = round(time, digits = 0)) 

##Calculate reversal probability

cleanrawsrev <- cleanrawsrev %>% 
  mutate(rev_prob = rev / (not_rev + rev)) 

##optional code to remove any bad observtions and/or plates

cleanrawsrev <- cleanrawsrev %>% 
  filter(!(rev_dist == "0")) 
cleanrawsrev <- cleanrawsrev %>% 
  filter(!(time == "709"))
cleanrawsrev <- cleanrawsrev %>% 
  filter(!(plate_id == "20201009_132231"))  

##Calculate reversal speed 

cleanrawsrev <- cleanrawsrev %>%
  mutate(rev_speed = rev_dist / rev_dur) 

##Reorder factors

cleanrawsrev$genotype <- factor(cleanrawsrev$genotype,
    levels = c('VG937N', 'VG937C25', 'VG937D', 'VG937A', 'VG937C1', 'N2C', ordered = TRUE))

##Mean rev data

mean_cleanrawsrev <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarize_all(mean) 

##Add stim number NOTE: this must be changed to fit your experiment parameters 

mean_cleanrawsrev$stimulus_num <- rep(1:31, times = 6) 

##SD calcs

prob_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(prob_sd = sd(rev_prob))
dur_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dur_sd = sd(rev_dur))
speed_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(speed_sd = sd(rev_speed))
dist_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dist_sd = sd(rev_dist))

##SEM calcs

prob_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(prob_sem = sd(rev_prob)/sqrt(length(rev_prob)))
dur_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dur_sem = sd(rev_dur)/sqrt(length(rev_dur)))
dist_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dist_sem = sd(rev_dist)/sqrt(length(rev_dist)))
speed_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(speed_sem = sd(rev_speed)/sqrt(length(rev_speed)))


```


```{r}
##Plots of mean reversal probability nlg-1::AID::GFP VS N2 both with no Auxin treatment

##Habituation unc-86::AID::GFP continous degradation vs. non-treated

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_1d_AID_C_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Habituation unc-3::AID::GFP continous degradation vs. non-treated and developmental degradtion/adult recovery

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937D"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937D"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_1d_AID_C_D_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937D"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937D"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_D_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937D"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937D"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39", "#EDBD44")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_D_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Habituation unc-3::AID::GFP continous degradation vs. non-treated and adult inactivation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_1d_AID_C_A_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_A_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_A_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Habituation unc-3::AID::GFP continous degradation vs. adult and developmental degradation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A", "VG937D"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A", "VG937D"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_1d_AID_C_A_D_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A", "VG937D"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A", "VG937D"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_A_D_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A", "VG937D"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937A", "VG937D"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "dodgerblue2", "#EDBD44", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C_A_D_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")


##Added graphs for 4mM continous comparison


mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937C1"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937C1"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 1) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_colour_manual(values = c("black", "#EDBD44", "brown")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
  theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(legend.position="none") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
  ggsave("unc86_1d_AID_C25_C1_prob.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")
  
#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937C1"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937C1"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) + 
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,4)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "#EDBD44", "brown")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration (S)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C25_C1_dur.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")

##Plot speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937C1"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("VG937N", "VG937C25", "VG937C1"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  geom_line(size = 1) +
  theme_classic() + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 1) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5)) +
  geom_point(aes(shape=genotype), size = 4.25, fill = "white", stroke = 1.25) +
  scale_shape_manual(values=c(16,16,16,16)) +
  scale_size_manual(values=c(4.25,4.25,4.25,4.25)) +
  scale_color_manual(values=c("black", "#EDBD44", "brown")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed (mm/s)") +
  theme(axis.line = element_line(colour = 'black', size = 2.25)) +
  theme(axis.ticks = element_line(colour = "black", size = 2.25)) +
   theme(axis.ticks.length= unit(.25, "cm")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 30)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 30)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  theme(legend.position="none") +
  ggsave("unc86_1d_AID_C25_C1_speed.jpeg", width = 7, height = 6, path = "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/habituation")


```



```{r}

##Basic morphology features analysis

##Bash loop to output reversals and basic morphology from tracker plates (to be run in terminal)

for folder in $( ls ); do java -jar /Users/troymcdiarmid/Desktop/Chore.jar --segment --shadowless --pixelsize 0.027 --minimum-move-body 2 --minimum-time 20 --output width,length,morphwidth,curve,area,midline,pathlen,bias,dir,angular,aspect,kink,crab,speed --plugin Reoutline::despike --plugin Respine --plugin MeasureReversal::tap::dt=1::collect=0.5 $folder; done

##Bash argument to grep all .dat files into a summary of morphology (to be run in terminal)

grep -H '[.]*' $(find . -name '*.dat') > data.smorph

cd ../..

```


```{r}
##The following code creates a dataframe with all morphology and baseline locomotion measures throughout the tracking session.

##Comand to read .smorph file in 

setwd("/Volumes/SAMWISE/Troy/reversibility/unc_86/VG937_1day_0212_2021/data")

rawsmorph <- read_table2("data.smorph", col_names = c("plate_id", "width", "length", "morphwidth", "curve", "area", "midline", "pathlen", "bias", "dir", "angular", "aspect", "kink", "crab", "speed"))

cleanrawsmorph <- rawsmorph %>% 
  separate(plate_id, into = c("garbage", "plate_id", "genotype"), sep ="/") %>%
  separate(genotype, into = c("genotype", "time"), sep = ":") %>% 
  separate(genotype, into = c("genotype", "tracker"), sep = "s_") %>% 
  separate(tracker, into = c("tracker", "date"), sep = "0") %>% 
  separate(genotype, into = c("genotype", "growth_conditions"), sep = "_") 
   

##Filtering not for tracker C becuase it delivered faulty taps

cleanrawsmorph <- cleanrawsmorph %>% 
  filter(!tracker == "C")

####Make time numeric and round time

cleanrawsmorph <- cleanrawsmorph %>% mutate(time = as.numeric(time)) %>% 
  mutate(time = round(time, digits = 0)) 

##Ordering the genotype factor for plotting
    
cleanrawsmorph$genotype <- factor(cleanrawsmorph$genotype,
    levels = c('VG937N', 'VG937C25', 'VG937D', 'VG937A', 'VG937C1', 'N2C', ordered = TRUE))

##Filter for relevant groups

cleanrawsmorph <- cleanrawsmorph %>% 
    filter(genotype %in% c('VG937N', 'VG937C25', 'VG937D', 'VG937A'))


##Filtering to exclude first 10s when the tracker has yet to calculate conistent measurements for certain metrics.

cleanrawsmorph <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 10, 1199))


```




```{r}

##Calculating significance accross all morphology metrics for dhc-1 heatmap


##Code to calculate mean of morphology metrics accross plates

cleanrawsmorph_baseline <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 300, 599))

mean_cleanrawsmorph <- cleanrawsmorph_baseline %>% 
  dplyr::select(genotype, plate_id, width:speed) 

mean_cleanrawsmorph <- mean_cleanrawsmorph %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 

##Calculating absolute means and Sds across genomes 

genotype_means <- mean_cleanrawsmorph %>% 
  summarise_all(mean) 

genotype_sds <- mean_cleanrawsmorph %>% 
  summarise_all(sd) 

##Calculating stats

pairwise.t.test(x = mean_cleanrawsmorph$length, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$width, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$midline, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$morphwidth, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$area, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$pathlen, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$bias, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$dir, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$angular, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$aspect, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$kink, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$crab, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH") 
pairwise.t.test(x = mean_cleanrawsmorph$speed, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_cleanrawsmorph$curve, g = mean_cleanrawsmorph$genotype, p.adjust.method = "BH")

ggplot(mean_cleanrawsmorph, aes(genotype, length, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, width, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, midline, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, morphwidth, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, area, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, pathlen, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, bias, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, dir, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, angular, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, aspect, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, kink, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, crab, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_cleanrawsmorph, aes(genotype, curve, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)

##Calculating significance for all sensory/learning metrics for dhc-1 heatmap 

Initial_revs <- cleanrawsrev %>%
  filter(time %in% c(600)) %>% 
  filter(genotype %in% c('VG937N', 'VG937C25', 'VG937D', 'VG937A'))

mean_initial_revs <- Initial_revs %>% 
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 
  

pairwise.t.test(x = mean_initial_revs$rev_prob, g = mean_initial_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_initial_revs$rev_dur, g = mean_initial_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_initial_revs$rev_dist, g = mean_initial_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_initial_revs$rev_speed, g = mean_initial_revs$genotype, p.adjust.method = "BH")

ggplot(mean_initial_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_initial_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_initial_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_initial_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)


Final_revs <- cleanrawsrev %>%
  filter(time %in% c(870:890)) %>% 
  filter(genotype %in% c('VG937N', 'VG937C25', 'VG937D', 'VG937A'))

mean_final_revs <- Final_revs %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 


pairwise.t.test(x = mean_final_revs$rev_prob, g = mean_final_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_final_revs$rev_dur, g = mean_final_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_final_revs$rev_speed, g = mean_final_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_final_revs$rev_dist, g = mean_final_revs$genotype, p.adjust.method = "BH")

ggplot(mean_final_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_final_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_final_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_final_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)



Spont_revs <- cleanrawsrev %>%
  filter(time %in% c(1190)) %>% 
  filter(genotype %in% c('VG937N', 'VG937C25', 'VG937D', 'VG937A'))

mean_spont_revs <- Spont_revs %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 


pairwise.t.test(x = mean_spont_revs$rev_prob, g = mean_spont_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_spont_revs$rev_dur, g = mean_spont_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_spont_revs$rev_dist, g = mean_spont_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_spont_revs$rev_speed, g = mean_spont_revs$genotype, p.adjust.method = "BH")


ggplot(mean_spont_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_spont_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_spont_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_spont_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)


all_revs <- cleanrawsrev %>%
  filter(genotype %in% c('VG937N', 'VG937C25', 'VG937D', 'VG937A')) 

mean_all_revs <- all_revs %>% 
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 

pairwise.t.test(x = mean_all_revs$rev_prob, g = mean_all_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_all_revs$rev_speed, g = mean_all_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_all_revs$rev_dur, g = mean_all_revs$genotype, p.adjust.method = "BH")
pairwise.t.test(x = mean_all_revs$rev_dist, g = mean_all_revs$genotype, p.adjust.method = "BH")

ggplot(mean_all_revs, aes(genotype, rev_prob, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_all_revs, aes(genotype, rev_dur, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_all_revs, aes(genotype, rev_speed, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)
ggplot(mean_all_revs, aes(genotype, rev_dist, colour = genotype)) +
  geom_jitter(size = 1, width = 0.25)


```



```{r}
##First ungroup the dataframe for statistical testing

UG_mean_cleanrawsmorph <- ungroup(mean_cleanrawsmorph) 

##Compute the t-statistics and p-values for all features

Length_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(length ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(length ~ genotype,
   data = UG_mean_cleanrawsmorph) 
length_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
length_results <- length_tstat_DF %>% 
  left_join(Length_pwt, by = "genotype") 

width_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(width ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(width ~ genotype,
   data = UG_mean_cleanrawsmorph) 
width_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
width_results <- width_tstat_DF %>% 
  left_join(width_pwt, by = "genotype") 

midline_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(midline ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(midline ~ genotype,
   data = UG_mean_cleanrawsmorph) 
midline_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
midline_results <- midline_tstat_DF %>% 
  left_join(midline_pwt, by = "genotype") 

morphwidth_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(morphwidth ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(morphwidth ~ genotype,
   data = UG_mean_cleanrawsmorph) 
morphwidth_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
morphwidth_results <- morphwidth_tstat_DF %>% 
  left_join(morphwidth_pwt, by = "genotype") 

area_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(area ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(area ~ genotype,
   data = UG_mean_cleanrawsmorph) 
area_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
area_results <- area_tstat_DF %>% 
  left_join(area_pwt, by = "genotype")

pathlen_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(pathlen ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(pathlen ~ genotype,
   data = UG_mean_cleanrawsmorph) 
pathlen_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
pathlen_results <- pathlen_tstat_DF %>% 
  left_join(pathlen_pwt, by = "genotype")

bias_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(bias ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(bias ~ genotype,
   data = UG_mean_cleanrawsmorph) 
bias_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
bias_results <- bias_tstat_DF %>% 
  left_join(bias_pwt, by = "genotype")

dir_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(dir ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(dir ~ genotype,
   data = UG_mean_cleanrawsmorph) 
dir_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
dir_results <- dir_tstat_DF %>% 
  left_join(dir_pwt, by = "genotype")

angular_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(angular ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(angular ~ genotype,
   data = UG_mean_cleanrawsmorph) 
angular_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
angular_results <- angular_tstat_DF %>% 
  left_join(angular_pwt, by = "genotype")

aspect_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(aspect ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(aspect ~ genotype,
   data = UG_mean_cleanrawsmorph) 
aspect_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
aspect_results <- aspect_tstat_DF %>% 
  left_join(aspect_pwt, by = "genotype")

kink_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(kink ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(kink ~ genotype,
   data = UG_mean_cleanrawsmorph) 
kink_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
kink_results <- kink_tstat_DF %>% 
  left_join(kink_pwt, by = "genotype")

crab_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(crab ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(crab ~ genotype,
   data = UG_mean_cleanrawsmorph) 
crab_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
crab_results <- crab_tstat_DF %>% 
  left_join(crab_pwt, by = "genotype")

speed_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(speed ~ genotype,
   data = UG_mean_cleanrawsmorph) 
speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
speed_results <- speed_tstat_DF %>% 
  left_join(speed_pwt, by = "genotype")

curve_pwt <- UG_mean_cleanrawsmorph  %>% 
  pairwise_t_test(curve ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(curve ~ genotype,
   data = UG_mean_cleanrawsmorph) 
curve_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
curve_results <- curve_tstat_DF %>% 
  left_join(curve_pwt, by = "genotype")


##Now ungrouping the initial revs

UG_mean_initial_revs <- ungroup(mean_initial_revs)

##Then calculating those four statistics 

init_rev_prob_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_prob_results <- init_rev_prob_tstat_DF %>% 
  left_join(init_rev_prob_pwt, by = "genotype")

init_rev_dur_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_dur_results <- init_rev_prob_tstat_DF %>% 
  left_join(init_rev_dur_pwt, by = "genotype")

init_rev_speed_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_speed_results <- init_rev_speed_tstat_DF %>% 
  left_join(init_rev_speed_pwt, by = "genotype")


init_rev_dist_pwt <- UG_mean_initial_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_initial_revs) 
init_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
init_rev_dist_results <- init_rev_dist_tstat_DF %>% 
  left_join(init_rev_dist_pwt, by = "genotype")

init_rev_results <- rbind(init_rev_prob_results, init_rev_dur_results, init_rev_speed_results, init_rev_dist_results) 

init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_prob")] <- "init_rev_prob"
init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_dur")] <- "init_rev_dur"
init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_speed")] <- "init_rev_speed"
init_rev_results$phenotype[which(init_rev_results$phenotype == "rev_dist")] <- "init_rev_dist"


##Then caclulating hab level

UG_mean_final_revs <- ungroup(mean_final_revs)

final_rev_prob_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_final_revs) 
final_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_prob_results <- final_rev_prob_tstat_DF %>% 
  left_join(final_rev_prob_pwt, by = "genotype")

final_rev_dur_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_final_revs) 
final_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_dur_results <- final_rev_dur_tstat_DF %>% 
  left_join(final_rev_dur_pwt, by = "genotype")

final_rev_speed_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_final_revs) 
final_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_speed_results <- final_rev_speed_tstat_DF %>% 
  left_join(final_rev_speed_pwt, by = "genotype")


final_rev_dist_pwt <- UG_mean_final_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_final_revs) 
final_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
final_rev_dist_results <- final_rev_dist_tstat_DF %>% 
  left_join(final_rev_dist_pwt, by = "genotype")

final_rev_results <- rbind(final_rev_prob_results, final_rev_dur_results, final_rev_speed_results, final_rev_dist_results) 

final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_prob")] <- "final_rev_prob"
final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_dur")] <- "final_rev_dur"
final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_speed")] <- "final_rev_speed"
final_rev_results$phenotype[which(final_rev_results$phenotype == "rev_dist")] <- "final_rev_dist"

##Then caclulating spont revs

UG_mean_spont_revs <- ungroup(mean_spont_revs)

spont_rev_prob_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_prob_results <- spont_rev_prob_tstat_DF %>% 
  left_join(spont_rev_prob_pwt, by = "genotype")

spont_rev_dur_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_dur_results <- spont_rev_dur_tstat_DF %>% 
  left_join(spont_rev_dur_pwt, by = "genotype")

spont_rev_speed_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_speed_results <- spont_rev_speed_tstat_DF %>% 
  left_join(spont_rev_speed_pwt, by = "genotype")


spont_rev_dist_pwt <- UG_mean_spont_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_spont_revs) 
spont_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
spont_rev_dist_results <- spont_rev_dist_tstat_DF %>% 
  left_join(spont_rev_dist_pwt, by = "genotype")

spont_rev_results <- rbind(spont_rev_prob_results, spont_rev_dur_results, spont_rev_speed_results, spont_rev_dist_results) 

spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_prob")] <- "spont_rev_prob"
spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_dur")] <- "spont_rev_dur"
spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_speed")] <- "spont_rev_speed"
spont_rev_results$phenotype[which(spont_rev_results$phenotype == "rev_dist")] <- "spont_rev_dist"


##Then caclulating all revs

UG_mean_all_revs <- ungroup(mean_all_revs)

all_rev_prob_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_prob ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_prob ~ genotype,
   data = UG_mean_all_revs) 
all_rev_prob_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_prob_results <- all_rev_prob_tstat_DF %>% 
  left_join(all_rev_prob_pwt, by = "genotype")

all_rev_dur_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_dur ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dur ~ genotype,
   data = UG_mean_all_revs) 
all_rev_dur_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_dur_results <- all_rev_dur_tstat_DF %>% 
  left_join(all_rev_dur_pwt, by = "genotype")

all_rev_speed_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_speed ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_speed ~ genotype,
   data = UG_mean_all_revs) 
all_rev_speed_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_speed_results <- all_rev_speed_tstat_DF %>% 
  left_join(all_rev_speed_pwt, by = "genotype")


all_rev_dist_pwt <- UG_mean_all_revs  %>% 
  pairwise_t_test(rev_dist ~ genotype, p.adjust.method = "BH") %>% 
  filter(group1 == "VG937N") %>% 
  rename(phenotype = .y., genotype = group2, control_group = group1) 
lmfit <- lm(rev_dist ~ genotype,
   data = UG_mean_all_revs) 
all_rev_dist_tstat_DF <- tidy(lmfit) %>% 
  filter(!term == "(Intercept)") %>% 
  separate(term, into = c("garbage", "genotype"), sep = 8) %>% 
  select(genotype:statistic)
all_rev_dist_results <- all_rev_dist_tstat_DF %>% 
  left_join(all_rev_dist_pwt, by = "genotype")

all_rev_results <- rbind(all_rev_prob_results, all_rev_dur_results, all_rev_speed_results, all_rev_dist_results) 

all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_prob")] <- "all_rev_prob"
all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_dur")] <- "all_rev_dur"
all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_speed")] <- "all_rev_speed"
all_rev_results$phenotype[which(all_rev_results$phenotype == "rev_dist")] <- "all_rev_dist"

##Combining everything together

results <- rbind(length_results, width_results, midline_results, morphwidth_results, area_results, pathlen_results, bias_results, dir_results, angular_results, aspect_results, kink_results, crab_results, speed_results, curve_results, init_rev_results, final_rev_results, spont_rev_results, all_rev_results) %>% rename(condition = genotype, t_statistic = statistic, control_n = n1, treatment_condition_n = n2) %>% 
  mutate(p_f = p.adj)

results$p_f[results$p_f > 0.01] <- 0
results$p_f[results$p_f > 0] <- 1

results <- results %>% 
  mutate(plot_sig_tstat = t_statistic*p_f)

##Writing CSV of results

unc86_L4_results <- results %>% 
  select(!"p.adj.signif")

write_csv(unc86_L4_results, "/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/run2/unc86_l4_results.csv")

##creating a transposed version for heatmapping

results_mat <- results %>% 
  select(condition, phenotype, t_statistic) %>% 
  pivot_wider(names_from = phenotype, values_from = t_statistic) %>%
  as.matrix()

##Adding colnames for heatmap

results_mat2 <- results_mat[,2:31]

colnames_mat <- results_mat[,2:31]


results_mat2 <- matrix(as.numeric(results_mat2), ncol = ncol(results_mat2))

colnames(results_mat2) <- colnames(colnames_mat)
rownames(results_mat2) <- results_mat[,1]

##plotting

col_fun = colorRamp2(c(-20, 0, 20), c("dodgerblue", "black", "yellow"))

Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"))

##Calculate degree of rescue 

abs_continous_effect_mat <- abs(results_mat2)
abs_continous_effect_mat <- t(abs_continous_effect_mat[1,])
abs_rescue_level_mat <- abs(results_mat2)
abs_rescue_level_mat <- t(abs_rescue_level_mat[3,])

rescue_amount_mat <- abs_continous_effect_mat-abs_rescue_level_mat
rescue_amount_mat[rescue_amount_mat < 0] <- 0

col_fun = colorRamp2(c(0, 5), c("white", "#86A790"))

png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/unc86_1D_rescue_amount_heatmap.png", width=1800, height=600, res=300)
 ht <- Heatmap(rescue_amount_mat, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.25, "mm"), show_row_names = FALSE)
 draw(ht, show_heatmap_legend = FALSE)
 dev.off()
 
png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/unc86_1D_rescue_amount_heatmap_leg.png", width=2000, height=600, res=300)
 ht <- Heatmap(rescue_amount_mat, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.25, "mm"))
 draw(ht)
 dev.off()

##Capping t-statistics 

results_mat2[results_mat2 < -5] <- -5
results_mat2[results_mat2 > 5] <- 5
  
##Making the heatmap

col_fun = colorRamp2(c(-5, 0, 5), c("dodgerblue", "black", "yellow"))

Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"))


##Plotting only significant values 

results_mat <- results %>% 
  select(condition, phenotype, plot_sig_tstat) %>% 
  pivot_wider(names_from = phenotype, values_from = plot_sig_tstat) %>% 
  as.matrix()

results_mat2 <- results_mat[,2:31]

colnames_mat <- results_mat[,2:31]


results_mat2 <- matrix(as.numeric(results_mat2), ncol = ncol(results_mat2))

colnames(results_mat2) <- colnames(colnames_mat)
rownames(results_mat2) <- results_mat[,1]

##Making the heatmap

results_mat2[results_mat2 < -10] <- -10
results_mat2[results_mat2 > 10] <- 10

col_fun = colorRamp2(c(-10, 0, 10), c("dodgerblue", "black", "yellow"))

png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/unc86_1D_heatmap.png", width=1800, height=600, res=300)
 ht <- Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"), show_row_names = FALSE)
 draw(ht, show_heatmap_legend = FALSE)
 dev.off()

png(file="/Users/troymcdiarmid/Documents/Reversibility_materials/Figures/unc86/1d_rev_run2/unc86_1D_heatmap_leg.png", width=2000, height=600, res=300)
 ht <- Heatmap(results_mat2, col = col_fun, rect_gp = gpar(col = "white", lwd = 5), cluster_rows = FALSE, cluster_columns = FALSE, height = 29*unit(0.55, "mm"))
 draw(ht)
 dev.off()

```

